# pre-commit hook is skipped if you only delete files, the 'always_run' setting helps with this scenario

repos:
  - repo: local
    hooks: 
    - id: kpt_hydrate
      name: hydrate source to deploy dir
      language: system
      # verbose to true if we always want to see the output, otherwise we'll only see when pre-commit fails
      verbose: true
      # pass_filenames to false avoids cases when the script is launched multiple times
      pass_filenames: false
      # always_run to true so it runs when changes only consists of deleted files
      always_run: true
      entry: bash tools/scripts/kpt/hydrate.sh
