apiVersion: v1
kind: ConfigMap
metadata:
  name: setters
  annotations:
    config.kubernetes.io/local-config: 'true'
data:
  # Used for naming of the root-sync
  ## id is the client-name
  id: client-name

  # Git repo values
  repo-url: https://AZDO-ORG@dev.azure.com/AZDO-ORG/AZDO-PROJECT/_git/REPO-NAME
  # repo-url: https://github.com/GITHUB-ORG/REPO-NAME # Alternate, GitHub
  repo-branch: main
  repo-dir: tier2/configcontroller/deploy/dev
